apiVersion: v1
kind: Service
metadata:
  name: simple-neo4j-svc
  namespace: "neo4j"
spec:
  type: NodePort
  selector:
    app: simple-neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      nodePort: 30001
    - name: bolt
      port: 7687
      targetPort: 7687
      nodePort: 30002
